apiVersion: kots.io/v1beta2
kind: HelmChart
metadata:
  name: simpleapp
spec:
  # chart identifies a matching chart from a .tgz
  chart:
    name: simpleapp
    chartVersion: 0.1.0
  namespace: simpleapp
  createNamespace: true
  optionalValues:
  - when: 'repl{{ eq Distribution "embedded-cluster" }}'
    recursiveMerge: false
    values:
      service:
        type: NodePort
        nodePorts:
          http: "32000"