apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simpleapp.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
{{ include "simpleapp.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "simpleapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "simpleapp.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: html-content
              mountPath: /usr/share/nginx/html
              readOnly: true
      volumes:
        - name: html-content
          configMap:
            name: {{ include "simpleapp.fullname" . }}-html
