---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapp
  namespace: simpleapp
  labels:
    app.kubernetes.io/name: simpleapp
    app.kubernetes.io/instance: simpleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: simpleapp
      app.kubernetes.io/instance: simpleapp
  template:
    metadata:
      labels:
        app.kubernetes.io/name: simpleapp
        app.kubernetes.io/instance: simpleapp
    spec:
      containers:
        - name: simpleapp
          image: "nginx:1.25"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - name: html-content
              mountPath: /usr/share/nginx/html
              readOnly: true
      volumes:
        - name: html-content
          configMap:
            name: simpleapp-html
