apiVersion: v1
kind: Service
metadata:
  name: simpleapp
  namespace: simpleapp
  labels:
    app.kubernetes.io/name: simpleapp
    app.kubernetes.io/instance: simpleapp
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: simpleapp
    app.kubernetes.io/instance: simpleapp