apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: {{ include "simpleapp.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "simpleapp.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "simpleapp.selectorLabels" . | nindent 6 }}
  componentKinds:
    - group: apps
      kind: Deployment
    - group: ""
      kind: Service
    - group: ""
      kind: ConfigMap 