apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "simpleapp.fullname" . }}-html
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "simpleapp.labels" . | nindent 4 }}
data:
  index.html: |
{{ .Values.htmlContent | indent 4 }}
